public class MathUtility 
{

    public static Integer addNumbers(List<Integer> lstNumbers)
    {
        Integer res = 0 ;

        return res ;
    }//end addNumbers

    public static Integer addNumbers(Integer Num1 , Integer Num2)
    {
        Integer res = 0 ;

        return res ;
    }//end addNumbers


    public static decimal divideNumbers(decimal num1 , decimal num2)
    {
        decimal res = 0 ;

        return res ;
    }

    public static Integer subtractNumbers(Integer Num1 , Integer Num2)
    {
        Integer res = 0 ;

        return res ;

    }
}//end class 